# Docs: https://docs.codecov.io/docs/codecovyml-reference

codecov:
  require_ci_to_pass: true

coverage:
  precision: 1
  round: down
  status:
    project:
      default:
        target: 96%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 1%
    changes: false

comment:
  layout: "diff,files"
  require_changes: true
