repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.3
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix", "--exclude", "migrations,node_modules,venv,build,dist,tests/data/config"]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.8.0
    hooks:
      - id: pyupgrade
        args: ["--py3-plus", "--py36-plus", "--py37-plus"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - django-stubs
          - djangorestframework
          - djangorestframework-stubs
          - types-PyYAML
          - drf-yasg
          - drf-spectacular
          - types-toml
          - setuptools

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        args: ["--extension-pkg-allow-list=orjson"]
        exclude: tests|test_project|manage.py
        additional_dependencies:
          - django
          - djangorestframework
          - inflection
          - openapi-spec-validator
          - prance
          - pyYAML
          - django-stubs
          - djangorestframework-stubs
          - drf_yasg
          - drf-spectacular
          - pylint
          - faker
          - orjson
          - toml
