name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            .venv
             ~/.cache/pre-commit
          key: ${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}-6
      - run: |
          python -m venv .venv --upgrade-deps
          source .venv/bin/activate
          pip install pre-commit
      - run: |
          source .venv/bin/activate
          pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8.14", "3.9.14", "3.10.7", "3.12.10"]
        django-version: ["4.2", "5.0", "5.1", "5.2"]
        exclude:
          - django-version: 5.0
            python-version: 3.8.14
          - django-version: 5.0
            python-version: 3.9.14
          - django-version: 5.1
            python-version: 3.8.14
          - django-version: 5.1
            python-version: 3.9.14
          - django-version: 5.2
            python-version: 3.8.14
          - django-version: 5.2
            python-version: 3.9.14
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          version: 1.3.2
      - uses: actions/cache@v3
        id: cache-venv
        with:
          path: .venv
          key: ${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}-6
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install wheel setuptools pip -U
          poetry install --no-interaction --no-root --extras drf-spectacular --extras drf-yasg --extras django-ninja
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - run: |
          source .venv/bin/activate
          pip install "Django==${{ matrix.django-version }}"
      - run: |
          source .venv/bin/activate
          coverage run -m pytest
          coverage xml
          coverage report
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
        if: matrix.python-version == '3.10.7' && matrix.django-version == '4.2'

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: coverage-xml
      - uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
